import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        primary: "#005244",
        "primary-container": "#146c5b",
        "on-primary": "#ffffff",
        "on-primary-container": "#9bead4",
        "primary-fixed": "#a3f2dc",
        "primary-fixed-dim": "#87d5c0",
        secondary: "#2d685b",
        "secondary-container": "#b2efde",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#346e61",
        tertiary: "#3f4a48",
        "tertiary-container": "#576260",
        error: "#C93B3B",
        "error-bg": "#FDECEC",
        "error-container": "#ffdad6",
        warning: "#B77900",
        "warning-bg": "#FFF5DC",
        success: "#16834B",
        "success-bg": "#EAF7EF",
        info: "#3478B8",
        "info-bg": "#EAF3FB",
        surface: "#FFFFFF",
        "surface-bright": "#f7faf7",
        "surface-container": "#ebefec",
        "surface-container-low": "#f1f4f1",
        "surface-container-high": "#e6e9e6",
        "surface-container-highest": "#e0e3e0",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e0",
        "surface-dim": "#d7dbd8",
        "surface-tint": "#116a5a",
        "on-surface": "#181c1b",
        "on-surface-variant": "#3f4945",
        "on-background": "#181c1b",
        "inverse-surface": "#2d3130",
        "inverse-primary": "#87d5c0",
        "inverse-on-surface": "#eef1ee",
        outline: "#6f7975",
        "outline-variant": "#bec9c4",
        "border-base": "#E3E8E6",
        "text-primary": "#17201D",
        "text-secondary": "#5E6864",
        "text-muted": "#8A9390",
        "bg-app": "#F7F9F8",
        background: "#f7faf7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-tablet": "24px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        display: ["Inter"],
        "page-title": ["Inter"],
        "section-title": ["Inter"],
        "card-title": ["Inter"],
        body: ["Inter"],
        button: ["Inter"],
        small: ["Inter"],
        "amount-lg": ["Inter"],
      },
      fontSize: {
        display: ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "page-title": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "section-title": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "card-title": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        body: ["14px", { lineHeight: "22px", fontWeight: "400" }],
        button: ["14px", { lineHeight: "20px", fontWeight: "600" }],
        small: ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "amount-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
export default config;
